name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to EC2 on dev and master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v1

      - name: Deploy to lxc instance 
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY2 }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
        
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY2 }}
          port: 22
          script: |
            cd ${{ secrets.TARGET_DIR }}
            source venv/bin/activate
            ${{ secrets.TARGET_DIR }}/venv/bin/pip3 install -r requirements.txt 
            rm ${{ secrets.TARGET_DIR }}/venv/static/*
            mkdir -p static
            bash s.sh
            pkill -9 uvicorn 
            sleep 3
            nohup ${{ secrets.TARGET_DIR }}/venv/bin/uvicorn be:app --host 0.0.0.0 --port 8000 &
            nohup ${{ secrets.TARGET_DIR }}/venv/bin/uvicorn be_app:app --host 0.0.0.0 --port 8090 &
            date
